@startuml
title 基于GitHub的实验管理平台--类图
class users {
    <b>user_id</b> （用户ID）
    name （用户真实姓名）
    github_username （用户GitHub账号）
    update_date （用户GitHub账号修改日期）
    password （用户密码）
    disable （用户是否禁用）
}
class teachers{
    <b>teacher_id</b> （老师工号）
    department （老师所属部门）
    courselist （老师选课列表）
    course_num （规定需选的课程数）
}
class students{
    <b>student_id</b> （学号）
    class （班级）
    courselist （学生选课列表）
    course_num （规定需选的课程数）
}
users <|- students
users <|-- teachers
class course{
    <b>course_id</b>  （课程号）
    course_name  （课程名称）
    max_stu （最多可容纳的学生人数）
    max_tea  （最多可容纳的教师人数）
    chooseNumber_stu  （选择该课程的学生人数）
    chooseNumber_tea  （选择该课程的教师人数）
    students（选择该课程的学生列表）
    teachers（选择该课程的老师列表）
}
class grade {
    <b>teacher_id</b> （老师编号）
    <b>grade_id</b> （评分标准编号）
    grade_standrand （评分标准）
    grade_weight （分数所占比重）
    grade（所得分数）
}
class tests {
    <b>student_id</b> （学生编号）
    <b>term_id</b> （学期编号）
    <b>course_id</b> （课程编号）
    <b>test_id</b> （实验编号）
    <b>grade_id</b> （实验评分编号）
    test_title （实验名称）
    avg （实验平均分）
    memo （评价）
    update_date （评改日期）
}
class term{
    <b>term_id</b> （学期编号）
    term_number （第几学期）
}
class department{
    <b>department_id</b> （部门编号）
    department_name （部门名称）
}
students "n" -- "n"  course
tests "1" -- "n"  grade
course "1" -- "n"  tests
teachers "n" -- "n"  course
term "1" -- "n"  course
students "n" -- "n"  term
teachers "n" -- "n"  term
teachers "n" -- "1"  department
teachers "1" -- "n"  grade

@enduml
