@startuml
title 基于GitHub的实验管理平台--修改实验用例的顺序图
actor teachers
teachers -> terms : 获取学期编号
terms -> courses : 获取课程编号
courses -> tests : 获取当前已发布的实验
tests -> grades_standard : 获取评分标准
grades_standard --> teachers : 返回界面
teachers -> tests : 修改并重新发布实验
@enduml
