@startuml
title 基于GitHub的实验管理平台--学生列表用例的顺序图
actor users
users -> students:查看所有学生列表
alt 如果users是老师
    users -> students:获取所有学生列表
	students -> term: 获取学期编号
    term -> course: 获取课程编号
    users <-- course: 通过term_id和course_id获取学号,查看该课程下的学生列表
else 如果users是students，或者未登录
    students --> users:每个学生的信息
end
@enduml
