@startuml
title 基于GitHub的实验管理平台--查看成绩用例的顺序图
actor users
users -> students : 输入学号
students -> grades : 获取所有成绩列表
grades -> terms : 获取学期编号
terms -> courses : 获取课程编号
courses -> tests : 获取实验
tests -> grades_standard : 获取评分标准选项
grades_standard --> users:每个实验的信息、成绩和评语
@enduml
