@startuml
title 基于GitHub的实验管理平台--登录用例的顺序图
actor users
alt 老师登录
    users -> teachers
    teachers->students
    students --> users:返回所有学生列表
else 学生登录
    users -> students
    users <-- students:返回所有学生列表
end
@enduml
