@startuml
title 基于GitHub的实验管理平台--学生列表用例的顺序图
actor users
alt 如果users是老师
    users -> teachers
	teachers -> students: 获取学生列表信息
    students --> users: 返回学生列表
else 如果users是students
    users -> students
    students --> users: 获取信息
end
@enduml
